// tradecity-ui/src/components/ui/button/TcButton.tsx
import {classes} from "../tools";
import {JSX, splitProps} from "solid-js";

interface TcButtonProps extends JSX.ButtonHTMLAttributes<HTMLButtonElement> {
    text: string;
    dangerous?: boolean;
    disabled?: boolean;
}

export default function TcButton(props: TcButtonProps) {
    const [local, buttonProps] = splitProps(props, ["text", "dangerous", "disabled", "class"]);

    return (
        <button
            {...buttonProps}
            class={classes("text-base m-1 py-0.5 px-2 rounded-sm hover:bg-dark-base", local.dangerous ? "bg-red-500" : "bg-base")}
            disabled={local.disabled}
        >
            { local.text }
        </button>
    )
}

// tradecity-ui/src/components/controls/button/TcButton.vue
<template>
<button type="button" :class="['text-sm rounded-sm px-2.5 py-0.5 m-0.5 border border-neutral-600', styles, !dangerous ? 'bg-primary hover:bg-secondary' : 'bg-red-500 hover:bg-red-400']">{{ text }}</button>
</template>

<script setup lang="ts">
interface TcButtonProps {
    text: string,
    dangerous?: boolean,
    styles?: string
}

withDefaults(defineProps<TcButtonProps>(), {
    dangerous: false
});
</script>

<style scoped>

</style>
