// tradecity-ui/src/components/ui/button/TcButton.tsx
import {classes} from "../tools";
import {JSX, splitProps} from "solid-js";

interface TcButtonProps extends JSX.ButtonHTMLAttributes<HTMLButtonElement> {
    text: string;
    dangerous?: boolean;
    disabled?: boolean;
}

export default function TcButton(props: TcButtonProps) {
    const [local, buttonProps] = splitProps(props, ["text", "dangerous", "disabled", "class"]);

    return (
        <button
            {...buttonProps}
            class={classes("text-base m-1 py-0.5 px-2 rounded-sm hover:bg-dark-base", local.dangerous ? "bg-red-500" : "bg-base")}
            disabled={local.disabled}
        >
            { local.text }
        </button>
    )
}

// tradecity-ui/src/components/ui/button/TcButton.vue
<template>
  <button
      :class="['text-base m-1 py-px px-2 rounded-sm font-medium', dangerous ? 'bg-red-500 hover:bg-red-700' : 'bg-base hover:bg-dark-base']"
      :disabled="disabled"
  >
    {{ text }}
  </button>
</template>

<script setup lang="ts">
interface TcButtonProps {
  text: string;
  dangerous?: boolean;
  disabled?: boolean;
}
defineProps<TcButtonProps>();
</script>

<style scoped>

</style>
